version: '3.1'

services:

  db:
    image: financas
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 852456

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080